version: "3.8"
services:
  postgresql:
    container_name: client-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=client_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/client_db
      - --username=admin
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  users-service:
    depends_on:
      - postgresql
    build: users/.
    environment:
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/client_db
    ports:
      - "8080:8080"
    networks:
      - backend

  tariffs-service:
    depends_on:
      - postgresql
    build: tariffs/.
    environment:
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/client_db
    ports:
      - "8082:8082"
    networks:
      - backend

  products-service:
    depends_on:
      - postgresql
    build: products/.
    environment:
      - tariffs_client_base_url=http://tariffs-service:8082/api/tariff
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/client_db
    ports:
      - "8081:8081"
    networks:
      - backend

  backend-service:
    depends_on:
      - products-service
      - tariffs-service
      - users-service
    build: backend-client-service/.
    environment:
      - products_client_base_url=http://products-service:8081/api/product
      - tariffs_client_base_url=http://tariffs-service:8082/api/tariff
    ports:
      - "8083:8083"
    networks:
      - backend

volumes:
  postgres:
networks:
  backend: