version: "3.8"
services:
  postgresql:
    container_name: client-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=client_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/client_db
      - --username=admin
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  users-service:
    depends_on:
      - postgresql
      - liquibase-migrations
    build: users/.
    environment:
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/client_db
#    ports:
#      - "8080:8080"
    networks:
      - backend

  tariffs-service:
    depends_on:
      - postgresql
      - liquibase-migrations
      - kafka
    build: tariffs/.
    environment:
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/client_db
      - products_client_base_url=http://localhost:8081/api/products
      - spring_kafka_bootstrap_servers=kafka:29092
#    ports:
#      - "8082:8082"
    networks:
      - backend

  products-service:
    depends_on:
      - tariffs-service
      - postgresql
      - liquibase-migrations
      - kafka
    build: products/.
    environment:
      - tariffs_client_base_url=http://tariffs-service:8082/api/tariffs
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/client_db
      - spring_kafka_bootstrap_servers=kafka:29092
#    ports:
#      - "8081:8081"
    networks:
      - backend

  backend-service:
    depends_on:
      - products-service
      - tariffs-service
      - users-service
    build: backend-client-service/.
    environment:
      - products_client_base_url=http://products-service:8081/api/products
      - tariffs_client_base_url=http://tariffs-service:8082/api/tariffs
    ports:
      - "8083:8083"
    networks:
      - backend

volumes:
  postgres:
networks:
  backend: