version: "3.8"
services:
  postgresql:
    container_name: client-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=account_db

    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  service:
    depends_on:
      - postgresql
    build: .
    environment:
      - spring_datasource_url=jdbc:postgresql://postgresql:5432/account_db
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres:
networks:
  backend: